#ifndef DASHBOARD_HTML_H
#define DASHBOARD_HTML_H

const char* dashboard_html = "<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>AirSense V4 Dashboard</title>\n"
"    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n"
"    <style>\n"
"        :root {\n"
"            --bg-color: #0f172a;\n"
"            --card-bg: #1e293b;\n"
"            --text-main: #f8fafc;\n"
"            --text-muted: #94a3b8;\n"
"            --accent-blue: #3b82f6;\n"
"            --accent-green: #10b981;\n"
"            --accent-yellow: #f59e0b;\n"
"            --accent-red: #ef4444;\n"
"        }\n"
"        body {\n"
"            font-family: 'Segoe UI', system-ui, sans-serif;\n"
"            background-color: var(--bg-color);\n"
"            color: var(--text-main);\n"
"            margin: 0;\n"
"            padding: 20px;\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            align-items: center;\n"
"        }\n"
"        h1 { margin-top: 0; font-weight: 600; color: #e2e8f0; }\n"
"        .dashboard {\n"
"            width: 100%;\n"
"            max-width: 1200px;\n"
"            display: grid;\n"
"            gap: 20px;\n"
"            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n"
"        }\n"
"        .panel {\n"
"            background-color: var(--card-bg);\n"
"            border-radius: 16px;\n"
"            padding: 24px;\n"
"            box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06);\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            position: relative;\n"
"            overflow: hidden;\n"
"        }\n"
"        .health-panel {\n"
"            grid-column: 1 / -1;\n"
"            text-align: center;\n"
"            padding: 30px;\n"
"            transition: all 0.3s ease;\n"
"        }\n"
"        .health-status {\n"
"            font-size: 2.5rem;\n"
"            font-weight: bold;\n"
"            margin: 10px 0;\n"
"            text-transform: uppercase;\n"
"            letter-spacing: 2px;\n"
"        }\n"
"        .status-safe { color: var(--accent-green); text-shadow: 0 0 20px rgba(16,185,129,0.4); }\n"
"        .status-warn { color: var(--accent-yellow); text-shadow: 0 0 20px rgba(245,158,11,0.4); }\n"
"        .status-danger { \n"
"            color: var(--accent-red); \n"
"            text-shadow: 0 0 20px rgba(239,68,68,0.6); \n"
"            animation: pulse 1s infinite alternate;\n"
"        }\n"
"        @keyframes pulse {\n"
"            from { box-shadow: 0 0 0 rgba(239,68,68,0); }\n"
"            to { box-shadow: inset 0 0 30px rgba(239,68,68,0.4); }\n"
"        }\n"
"        .card-header {\n"
"            display: flex;\n"
"            justify-content: space-between;\n"
"            align-items: center;\n"
"            margin-bottom: 16px;\n"
"        }\n"
"        .card-title { font-size: 1.1rem; color: var(--text-muted); margin: 0; }\n"
"        .card-icon { font-size: 1.8rem; }\n"
"        .card-value { font-size: 2.5rem; font-weight: bold; margin: 0; }\n"
"        .card-unit { font-size: 1rem; color: var(--text-muted); font-weight: normal; }\n"
"        .charts-container { grid-column: 1 / -1; display: grid; gap: 20px; grid-template-columns: 1fr 1fr; }\n"
"        .log-panel { grid-column: 1 / -1; max-height: 200px; overflow-y: auto; }\n"
"        .log-panel h3 { margin: 0 0 12px 0; color: var(--text-muted); font-size: 1rem; }\n"
"        .log-entry { padding: 6px 10px; margin: 4px 0; border-radius: 6px; font-size: 0.85rem; }\n"
"        .log-danger { background: rgba(239,68,68,0.15); color: #fca5a5; border-left: 3px solid #ef4444; }\n"
"        .log-warn { background: rgba(245,158,11,0.15); color: #fcd34d; border-left: 3px solid #f59e0b; }\n"
"        .log-safe { background: rgba(16,185,129,0.1); color: #6ee7b7; border-left: 3px solid #10b981; }\n"
"        @media (max-width: 768px) { .charts-container { grid-template-columns: 1fr; } }\n"
"        canvas { width: 100% !important; height: 300px !important; }\n"
"        .loading {\n"
"            position: absolute; top: 0; left: 0; right: 0; height: 3px;\n"
"            background: linear-gradient(90deg, transparent, var(--accent-blue), transparent);\n"
"            background-size: 200% 100%;\n"
"            animation: loadingBar 2s linear infinite;\n"
"            display: none;\n"
"        }\n"
"        @keyframes loadingBar { 0% { background-position: 100% 0; } 100% { background-position: -100% 0; } }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"dashboard\">\n"
"        <div class=\"panel health-panel\" id=\"healthPanel\">\n"
"            <div class=\"loading\" id=\"loader\"></div>\n"
"            <h2 style=\"margin:0; color:#94a3b8; font-weight:normal\">System Status</h2>\n"
"            <div class=\"health-status status-safe\" id=\"valStatus\">SAFE</div>\n"
"            <p id=\"statusMsg\" style=\"margin:0; color:#cbd5e1\">Initializing, Waiting for ESP32 Connection...</p>\n"
"        </div>\n"
"\n"
"        <div class=\"panel\">\n"
"            <div class=\"card-header\">\n"
"                <h3 class=\"card-title\">Temperature</h3>\n"
"                <span class=\"card-icon\">&#x1F321;&#xFE0F;</span>\n"
"            </div>\n"
"            <p class=\"card-value\"><span id=\"valTemp\">--</span><span class=\"card-unit\">&deg;C</span></p>\n"
"        </div>\n"
"\n"
"        <div class=\"panel\">\n"
"            <div class=\"card-header\">\n"
"                <h3 class=\"card-title\">Humidity</h3>\n"
"                <span class=\"card-icon\">&#x1F4A7;</span>\n"
"            </div>\n"
"            <p class=\"card-value\"><span id=\"valHum\">--</span><span class=\"card-unit\">%</span></p>\n"
"        </div>\n"
"\n"
"        <div class=\"panel\">\n"
"            <div class=\"card-header\">\n"
"                <h3 class=\"card-title\">Flammable Gas (MQ-2)</h3>\n"
"                <span class=\"card-icon\">&#x1F4A8;</span>\n"
"            </div>\n"
"            <p class=\"card-value\"><span id=\"valMq2\">--</span><span class=\"card-unit\" style=\"font-size:0.8rem\"> raw</span></p>\n"
"        </div>\n"
"\n"
"        <div class=\"panel\">\n"
"            <div class=\"card-header\">\n"
"                <h3 class=\"card-title\">Carbon Monoxide (MQ-7)</h3>\n"
"                <span class=\"card-icon\">&#x1F534;</span>\n"
"            </div>\n"
"            <p class=\"card-value\"><span id=\"valMq7\">--</span><span class=\"card-unit\" style=\"font-size:0.8rem\"> raw</span></p>\n"
"        </div>\n"
"\n"
"        <div class=\"panel\">\n"
"            <div class=\"card-header\">\n"
"                <h3 class=\"card-title\">Flame Sensor</h3>\n"
"                <span class=\"card-icon\">&#x1F525;</span>\n"
"            </div>\n"
"            <p class=\"card-value\" id=\"valFlame\" style=\"font-size:2rem\">Waiting</p>\n"
"        </div>\n"
"\n"
"        <div class=\"panel log-panel\" id=\"logPanel\">\n"
"            <h3>&#x1F4CB; Event Log</h3>\n"
"            <div id=\"logEntries\"></div>\n"
"        </div>\n"
"\n"
"        <div class=\"charts-container\">\n"
"            <div class=\"panel\"><canvas id=\"chartTempHum\"></canvas></div>\n"
"            <div class=\"panel\"><canvas id=\"chartGas\"></canvas></div>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <script>\n"
"        const maxDataPoints = 30;\n"
"        const maxLogEntries = 50;\n"
"        let timeLabels = [];\n"
"        let tempHistory = [];\n"
"        let humHistory = [];\n"
"        let mq2History = [];\n"
"        let mq7History = [];\n"
"        let prevState = 'safe';\n"
"\n"
"        Chart.defaults.color = '#94a3b8';\n"
"        Chart.defaults.font.family = 'Segoe UI';\n"
"\n"
"        const commonOptions = {\n"
"            responsive: true, maintainAspectRatio: false,\n"
"            plugins: { legend: { position: 'top' } },\n"
"            scales: {\n"
"                x: { grid: { color: 'rgba(255,255,255,0.05)' } },\n"
"                y: { grid: { color: 'rgba(255,255,255,0.05)' }, beginAtZero: true }\n"
"            },\n"
"            animation: { duration: 400 }\n"
"        };\n"
"\n"
"        const ctxTH = document.getElementById('chartTempHum').getContext('2d');\n"
"        const chartTH = new Chart(ctxTH, {\n"
"            type: 'line',\n"
"            data: {\n"
"                labels: timeLabels,\n"
"                datasets: [\n"
"                    { label: 'Temperature (\\u00B0C)', data: tempHistory, borderColor: '#f59e0b', backgroundColor: 'rgba(245,158,11,0.1)', tension: 0.4, fill: true },\n"
"                    { label: 'Humidity (%)', data: humHistory, borderColor: '#3b82f6', backgroundColor: 'rgba(59,130,246,0.1)', tension: 0.4, fill: true }\n"
"                ]\n"
"            },\n"
"            options: commonOptions\n"
"        });\n"
"\n"
"        const ctxGas = document.getElementById('chartGas').getContext('2d');\n"
"        const chartGas = new Chart(ctxGas, {\n"
"            type: 'line',\n"
"            data: {\n"
"                labels: timeLabels,\n"
"                datasets: [\n"
"                    { label: 'MQ-2 (Flammable Gas)', data: mq2History, borderColor: '#10b981', tension: 0.4 },\n"
"                    { label: 'MQ-7 (CO)', data: mq7History, borderColor: '#ef4444', tension: 0.4 }\n"
"                ]\n"
"            },\n"
"            options: commonOptions\n"
"        });\n"
"\n"
"        function getTimeStr() {\n"
"            const now = new Date();\n"
"            return now.getHours().toString().padStart(2,'0') + ':' + now.getMinutes().toString().padStart(2,'0') + ':' + now.getSeconds().toString().padStart(2,'0');\n"
"        }\n"
"\n"
"        function addLog(msg, level) {\n"
"            const container = document.getElementById('logEntries');\n"
"            const entry = document.createElement('div');\n"
"            entry.className = 'log-entry log-' + level;\n"
"            entry.textContent = '[' + getTimeStr() + '] ' + msg;\n"
"            container.insertBefore(entry, container.firstChild);\n"
"            while (container.children.length > maxLogEntries) container.removeChild(container.lastChild);\n"
"        }\n"
"\n"
"        function updateStatus(temp, hum, mq2, mq7, flame) {\n"
"            const healthStatus = document.getElementById('valStatus');\n"
"            const statusMsg = document.getElementById('statusMsg');\n"
"            const healthPanel = document.getElementById('healthPanel');\n"
"\n"
"            let state = 'safe';\n"
"            let warnings = [];\n"
"\n"
"            if (flame === 0) {\n"
"                state = 'danger';\n"
"                warnings.push('FLAME DETECTED! Evacuate the area immediately!');\n"
"            }\n"
"            if (mq2 > 3500) {\n"
"                state = 'danger';\n"
"                warnings.push('Critical flammable gas! Ventilate NOW! Do not use open flames or switches!');\n"
"            } else if (mq2 > 2000) {\n"
"                if (state !== 'danger') state = 'warn';\n"
"                warnings.push('Flammable gas rising. Open windows and ventilate the area.');\n"
"            }\n"
"            if (mq7 > 3500) {\n"
"                state = 'danger';\n"
"                warnings.push('Critical CO level! Ventilate immediately! Leave the area if possible!');\n"
"            } else if (mq7 > 2000) {\n"
"                if (state !== 'danger') state = 'warn';\n"
"                warnings.push('CO level rising. Check gas appliances and ventilate.');\n"
"            }\n"
"            if (temp > 50) {\n"
"                state = 'danger';\n"
"                warnings.push('Extreme temperature! Check for fire or heat source!');\n"
"            } else if (temp > 40) {\n"
"                if (state !== 'danger') state = 'warn';\n"
"                warnings.push('High temperature detected. Monitor the environment.');\n"
"            }\n"
"\n"
"            let msg = warnings.length > 0 ? warnings.join(' | ') : 'All sensor values are within normal range.';\n"
"\n"
"            healthPanel.className = 'panel health-panel';\n"
"            if (state === 'safe') {\n"
"                healthStatus.textContent = 'SAFE';\n"
"                healthStatus.className = 'health-status status-safe';\n"
"            } else if (state === 'warn') {\n"
"                healthStatus.textContent = 'CAUTION';\n"
"                healthStatus.className = 'health-status status-warn';\n"
"            } else {\n"
"                healthStatus.textContent = 'DANGER';\n"
"                healthStatus.className = 'health-status status-danger';\n"
"                healthPanel.classList.add('status-danger');\n"
"            }\n"
"            statusMsg.textContent = msg;\n"
"\n"
"            if (state !== prevState || state !== 'safe') {\n"
"                for (let i = 0; i < warnings.length; i++) {\n"
"                    addLog(warnings[i], state === 'danger' ? 'danger' : 'warn');\n"
"                }\n"
"                if (state === 'safe' && prevState !== 'safe') {\n"
"                    addLog('All clear. System returned to safe state.', 'safe');\n"
"                }\n"
"            }\n"
"            prevState = state;\n"
"\n"
"            document.getElementById('valFlame').innerHTML = flame === 0 ?\n"
"                '<span style=\"color:#ef4444\">FIRE DETECTED</span>' :\n"
"                '<span style=\"color:#10b981\">No Fire</span>';\n"
"        }\n"
"\n"
"        function updateCharts(temp, hum, mq2, mq7) {\n"
"            const timeStr = getTimeStr();\n"
"            timeLabels.push(timeStr);\n"
"            tempHistory.push(temp);\n"
"            humHistory.push(hum);\n"
"            mq2History.push(mq2);\n"
"            mq7History.push(mq7);\n"
"\n"
"            if (timeLabels.length > maxDataPoints) {\n"
"                timeLabels.shift();\n"
"                tempHistory.shift();\n"
"                humHistory.shift();\n"
"                mq2History.shift();\n"
"                mq7History.shift();\n"
"            }\n"
"\n"
"            chartTH.update();\n"
"            chartGas.update();\n"
"        }\n"
"\n"
"        async function fetchData() {\n"
"            document.getElementById('loader').style.display = 'block';\n"
"            try {\n"
"                const response = await fetch('/api/data');\n"
"                const data = await response.json();\n"
"\n"
"                document.getElementById('valTemp').textContent = data.temp.toFixed(1);\n"
"                document.getElementById('valHum').textContent = data.hum.toFixed(1);\n"
"                document.getElementById('valMq2').textContent = data.mq2;\n"
"                document.getElementById('valMq7').textContent = data.mq7;\n"
"\n"
"                updateStatus(data.temp, data.hum, data.mq2, data.mq7, data.flame);\n"
"                updateCharts(data.temp, data.hum, data.mq2, data.mq7);\n"
"            } catch (error) {\n"
"                console.error('Data fetch error:', error);\n"
"            } finally {\n"
"                document.getElementById('loader').style.display = 'none';\n"
"            }\n"
"        }\n"
"\n"
"        fetchData();\n"
"        setInterval(fetchData, 2500);\n"
"    </script>\n"
"</body>\n"
"</html>\n";

#endif // DASHBOARD_HTML_H
